FORMAT: 1A
HOST: http://www.google.com

# Appliance API
Appliance API is a *home automation* application allowing control over appliances using data from a network of sensors.

# Group Appliance
Appliance related resources of the **Appliance API**

## Appliance Collection [/appliances]
### List all Appliances [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Heating", "status": "off", "controlling-mote-id": 1
        }, {
          "id": 2, "title": "Air Conditioner", "status": "off", "controlling-mote-id": 2
        }, {
          "id": 3, "title": "Fan", "status": "off", "controlling-mote-id": 2
        }, {
          "id": 4, "title": "Door Bell", "status": "off", "controlling-mote-id": 4
        }, {
          "id": 5, "title": "Laundry Room Ceiling Lamp", "status": "off", "controlling-mote-id": 5
        }]

### Create an Appliance [POST]
+ Request (application/json)

        { "title": "Appliance" }

+ Response 201 (application/json)

        { "id": 6, "title": "Appliance", "controlling-mote-id": 1 }

## Appliance [/appliances/{id}]
A single Appliance object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve an Appliance [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 1, "title": "Heating", "controlling-mote-id": 1 }

### Remove an Appliance [DELETE]
+ Response 204


# Group Mote
Mote related resources of the **Appliance API**

## Mote Collection [/motes]
### List all Motes [GET]
+ Response 200 (application/json)

        [{
          "id": 0, "title": "beaglebone", "location": "office",
          "sensor-ids": [ 0, 1, 2 ] 
        }, {
          "id": 1, "title": "basement mote", "location": "basement",
          "sensor-ids": [ 1, 3, 4 ]
        }, {
          "id": 2, "title": "hallway mote", "location": "1st floor hallway",
          "sensor-ids": [ 1, 2 ]
        }, {
          "id": 3, "title": "porch mote", "location": "front porch",
          "sensor-ids": [ 3, 4 ]
        }, {
          "id": 4, "title": "laundry mote", "location": "laundry",
          "sensor-ids": [ 3, 4 ]
        }]

### Create a Mote [POST]
+ Request (application/json)

        { "title": "kitchen mote", "location": "kitchen", "sensor-ids": [ 3 ] }

+ Response 201 (application/json)

        { "id": 5, "title": "kitchen mote", "location": "kitchen", "sensor-ids": [ 3 ] }

## Mote [/motes/{id}]
A single Mote object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Sensor [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 1, "title": "basement mote", "location": "basement", "sensor-ids": [ 1, 3, 4 ] }

### Remove a Mote [DELETE]
+ Response 204


# Group Sensor
Sensor related resources of the **Appliance API**

## Sensor Collection [/sensors]
### List all Sensors [GET]
+ Response 200 (application/json)

        [{
          "id": 0, "title": "real time clock", "unit": "time"
        }, {
          "id": 1, "title": "temperature sensor", "unit": "Celsius"
        }, {
          "id": 2, "title": "humidity sensor", "unit": "%"
        }, {
          "id": 3, "title": "PIR detector", "unit": "binary"
        }, {
          "id": 4, "title": "ambient light sensor", "unit": "%"
        }, {
          "id": 5, "title": "reed switch", "unit": "binary"
        }]

### Create a Sensor [POST]
+ Request (application/json)

        { "title": "contact switch", "unit": "binary" }

+ Response 201 (application/json)

        { "id": 6, "title": "contact switch", "unit": "binary" }


## Sensor [/sensors/{id}]
A single Sensor object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Sensor [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 1, "temperature sensor", "unit": "Celsius" }

### Remove a Sensor [DELETE]
+ Response 204


# Group ControlRule
ControlRule related resources of the **Appliance API**

## ControlRule Collection [/controlrules]
### List all ControlRules [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "heating on weekday morning temperature rule", "actions": {
            { "appliance-id": 1, "set-status": "on" }
          }, "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Monday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Friday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "06:00:00" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "lt", "value": "08:30:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "lt", "value": "17.5" }
          } 
        }, {
          "id": 2, "title": "heating off weekday morning temperature rule", "actions": {
            { "appliance-id": 1, "set-status": "off" }
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Monday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Friday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "08:30:00" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "lt", "value": "17:00:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "gt", "value": "18.5" }
          } 
        }, {
          "id": 3, "title": "heating on weekday evening temperature rule", "actions": {
            { "appliance-id": 1, "set-status": "on" } 
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Monday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Friday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "17:00:00" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "lt", "value": "22:00:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "lt", "value": "17.5" }
          } 
        }, {
          "id": 4, "title": "heating off weekday evening temperature rule", "actions": {
            { "appliance-id": 1, "set-status": "off" }
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Monday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Friday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "22:00:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "gt", "value": "18.5" }
          } 
        }, {
          "id": 5, "title": "heating on weekend morning temperature rule", "actions": {
            { "appliance-id": 1, "set-status": "on" }
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Saturday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Sunday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "06:30:00" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "lt", "value": "10:00:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "lt", "value": "17.5" }
          } 
        }, {
          "id": 6, "title": "heating off weekend morning temperature rule", "actions": {
            { "appliance-id": 1, "set-status": "off" } 
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Saturday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Sunday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "10:00:00" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "lt", "value": "17:00:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "gt", "value": "18.5" }
          } 
        }, {
          "id": 7, "title": "heating on weekend evening temperature rule", "actions": 
            { "appliance-id": 1, "set-status": "on" } 
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Saturday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Sunday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "17:00:00" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "lt", "value": "22:00:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "lt", "value": "17.5" }
          } 
        }, {
          "id": 8, "title": "heating off weekend evening temperature rule", "actions": {
            { "appliance-id": 1, "set-status": "off" } 
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Saturday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Sunday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "22:00:00" },
            { "mote-id": 2, "sensor-index": 1, "value": "humidity", "operator": "gt", "value": "" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "gt", "value": "18.5" }
          } 
        }, {
          "id": 9, "title": "AC on weekday morning humidity rule", "actions": {
            { "appliance-id": 2, "set-status": "on" }, 
            { "appliance-id": 3, "set-status": "on" } 
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Monday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Friday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "06:00:00" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "lt", "value": "08:30:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "gt", "value": "26.5" },
            { "mote-id": 2, "sensor-index": 0, "value": "humidity", "operator": "gt", "value": "0.80" }
          } 
        }, {
          "id": 10, "title": "AC off weekday morning humidity rule", "actions": {
            { "appliance-id": 2, "set-status": "off" }, 
            { "appliance-id": 3, "set-status": "off" } 
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Monday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Friday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "08:30:00" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "lt", "value": "17:00:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "lt", "value": "27.5" },
            { "mote-id": 2, "sensor-index": 0, "value": "humidity", "operator": "lt", "value": "0.70" }
          } 
        }, {
          "id": 11, "title": "AC on weekday evening humidity rule", "actions": {
            { "appliance-id": 2, "set-status": "on" }, 
            { "appliance-id": 3, "set-status": "on" } 
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Monday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Friday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "17:00:00" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "lt", "value": "22:00:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "gt", "value": "26.5" },
            { "mote-id": 2, "sensor-index": 0, "value": "humidity", "operator": "gt", "value": "0.80" }
          } 
        }, {
          "id": 12, "title": "AC off weekday evening humidity rule", "actions": {
            { "appliance-id": 2, "set-status": "off" }, 
            { "appliance-id": 3, "set-status": "off" } 
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Monday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Friday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "22:00:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "lt", "value": "27.5" },
            { "mote-id": 2, "sensor-index": 0, "value": "humidity", "operator": "lt", "value": "0.70" }
          } 
        }, {
          "id": 13, "title": "AC on weekend morning humidity rule", "actions": {
            { "appliance-id": 2, "set-status": "on" }, 
            { "appliance-id": 3, "set-status": "on" } 
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Saturday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Sunday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "06:30:00" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "lt", "value": "10:00:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "gt", "value": "26.5" },
            { "mote-id": 2, "sensor-index": 0, "value": "humidity", "operator": "gt", "value": "0.80" }
          } 
        }, {
          "id": 14, "title": "AC off weekend morning humidity rule", "actions": {
            { "appliance-id": 2, "set-status": "off" }, 
            { "appliance-id": 3, "set-status": "off" } 
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Saturday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Sunday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "10:00:00" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "lt", "value": "17:00:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "lt", "value": "27.5" },
            { "mote-id": 2, "sensor-index": 0, "value": "humidity", "operator": "lt", "value": "0.70" }
          } 
        }, {
          "id": 15, "title": "AC on weekend evening humidity rule", "actions": {
            { "appliance-id": 2, "set-status": "on" }, 
            { "appliance-id": 3, "set-status": "on" } 
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Saturday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Sunday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "17:00:00" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "lt", "value": "22:00:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "gt", "value": "26.5" },
            { "mote-id": 2, "sensor-index": 0, "value": "humidity", "operator": "gt", "value": "0.80" }
          } 
        }, {
          "id": 16, "title": "AC off weekend evening humidity rule", "actions": {
            { "appliance-id": 2, "set-status": "off" }, 
            { "appliance-id": 3, "set-status": "off" } 
          } , "conditions": { 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "ge", "value": "Saturday" }, 
            { "mote-id": 0, "sensor-index": 0, "value": "day", "operator": "lt", "value": "Sunday" },
            { "mote-id": 0, "sensor-index": 0, "value": "time", "operator": "ge", "value": "22:00:00" },
            { "mote-id": 2, "sensor-index": 0, "value": "temperature", "operator": "lt", "value": "27.5" },
            { "mote-id": 2, "sensor-index": 0, "value": "humidity", "operator": "lt", "value": "0.70" }
          } 
        }]

### Create a ControlRule [POST]
+ Request (application/json)

        { "title": "contact switch", "unit": "binary" }

+ Response 201 (application/json)

        { "id": 6, "title": "contact switch", "unit": "binary" }


## ControlRule [/controlrules/{id}]
A single ControlRule object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a ControlRule [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 1, "temperature sensor", "unit": "Celsius" }

### Remove a ControlRule
+ Response 204
