FORMAT: 1A
HOST: http://www.google.com

# Appliance API
Appliance API is a *home automation* application allowing control over appliances using data from a network of sensors.

# Group Appliance
Appliance related resources of the **Appliance API**

## Appliance Collection [/notes]
### List all Appliances [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Heating",
        }, {
          "id": 2, "title": "Air Conditioner"
        }, {
          "id": 3, "title": "Fan"
        }, {
          "id": 4, "title": "Door Bell"
        }, {
          "id": 5, "title": "Laundry Room Ceiling Lamp"
        }]

### Create an Appliance [POST]
+ Request (application/json)

        { "title": "Appliance" }

+ Response 201 (application/json)

        { "id": 6, "title": "Appliance" }

## Appliance [/appliances/{id}]
A single Appliance object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve an Appliance [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 1, "title": "Heating" }

### Remove an Appliance [DELETE]
+ Response 204
